language: python

script: 
  PYTHONPATH=.:$PYTHONPATH py.test staxx_exporter.py

before_deploy:
- pip install sphinx
- pip install sphinx_rtd_theme
- pip install sphinx-argparse
- cd docs
- ./build_docs.sh
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: html  
  target_branch: gh-pages

  on:
    branch: master

