language: python

script: 
  PYTHONPATH=.:$PYTHONPATH py.test staxx_exporter.py

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: html  
  target_branch: gh-pages
  script: run_doc.sh
  on:
    branch: master

